version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcdf
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-dump:/docker-entrypoint-initdb.d  # Mount the dump directory for initialization

volumes:
  pgdata:
